# Generated by Django 4.0.5 on 2022-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_tracks'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_list', to='users.user'),
        ),
    ]
