# Generated by Django 4.0.5 on 2022-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_tracks'),
        ('tracks', '0002_track_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='predicted_genre',
            field=models.CharField(choices=[('Jazz', 'Jazz'), ('Disco', 'Disco'), ('Rap', 'Rap'), ('Rock', 'Rock')], default='Rock', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='track_list', to='users.user'),
        ),
    ]
