services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    container_name: fastapi
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    command: bash -c "python training_db.py && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  web:
    container_name: react
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  postgres_data: