services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      - POSGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  api:
    container_name: django
    build:
      context: ./api
    env_file:
      - ./api/.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  web:
    container_name: react
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  postgres_data: