# Generated by Django 4.0.5 on 2022-06-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tracks',
        ),
    ]
